version: "3.9"

x-django-env: &django-env
  DJANGO_DEBUG: false
  DJANGO_SETTINGS_MODULE: notify.settings
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

  DATABASE_DB: ${DATABASE_DB}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT}

  CELERY_BROKER_URL: ${CELERY_BROKER_URL}

  SYSTEM_BASE_URL: https://notify.lipasync.com

x-app-image: &app-image ${IMAGE_TAG}

networks:
  default:
    name: ${SHARED_NETWORK}
    external: true

services:
  notify:
    image: *app-image
    container_name: prod_notify_app
    environment:
      <<: *django-env
    ports:
      - "8016:8000"
    restart: always

  celery_worker:
    image: *app-image
    container_name: prod_notify_celery_worker
    command: celery -A notify worker -l INFO
    environment:
      <<: *django-env
    restart: always

  celery_beat:
    image: *app-image
    container_name: prod_notify_celery_beat
    command: celery -A notify beat -l INFO
    environment:
      <<: *django-env
    restart: always
