# Generated by Django 5.1.7 on 2025-03-23 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='notification_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='to',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='class_name',
            field=models.CharField(default='', help_text='Callback class containing its config', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='config',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='notification_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.notificationtype'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notificationtype')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template'),
        ),
        migrations.DeleteModel(
            name='ProviderConfig',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
    ]
