# Generated by Django 5.1.7 on 2025-03-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_notificationtemplate_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='code',
        ),
    ]
