# Generated by Django 4.2.11 on 2025-03-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_template_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='data',
            new_name='context',
        ),
    ]
