# Generated by Django 5.1.7 on 2025-03-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_data_notification_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.TextField(help_text='One recipient or comma-separated multiple recipients'),
        ),
    ]
