# Generated by Django 5.1.7 on 2025-03-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
