# Generated by Django 5.1.7 on 2025-04-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification_unique_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
