# Generated by Django 5.1.7 on 2025-04-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.JSONField(default=list),
        ),
    ]
