# Generated by Django 5.1.7 on 2025-04-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
