# Generated by Django 5.1.7 on 2025-06-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organisation_notification_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='system',
            name='callback_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='system',
            name='callback_type',
            field=models.CharField(choices=[('queue', 'Queue'), ('webhook', 'Webhook')], default='webhook', max_length=20),
        ),
        migrations.AddField(
            model_name='system',
            name='queue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='webhook_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='default_from_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]


