# Generated by Django 5.1.7 on 2025-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organisation_notification_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='callback_type',
            field=models.CharField(choices=[('queue', 'Queue'), ('webhook', 'Webhook')], default='webhook', max_length=20),
        ),
        migrations.AddField(
            model_name='system',
            name='queue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='webhook_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
