# Generated by Django 5.1.7 on 2025-06-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notificationtype_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='webhook_auth_token',
            new_name='webhook_api_key',
        ),
    ]
