# Generated by Django 5.1.7 on 2025-07-15 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_webhook_auth_token_system_webhook_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='config',
            new_name='default_config',
        ),
        migrations.CreateModel(
            name='SystemProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.system')),
            ],
            options={
                'ordering': ('system__name', 'provider__name'),
                'unique_together': {('system', 'provider')},
            },
        ),
    ]
