# Generated by Django 5.1.7 on 2025-07-15 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('core', '0014_rename_config_provider_default_config_and_more'),
    ]
