# Generated by Django 5.1.7 on 2025-07-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_notification_status_delete_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('Confirmation Pending', 'Confirmation Pending')], default='Pending', max_length=20),
        ),
    ]
