# Generated by Django 5.1.7 on 2025-07-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_notification_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.RemoveField(
            model_name='system',
            name='default_from_email',
        ),
    ]
