# Generated by Django 5.1.7 on 2025-07-15 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_alter_notification_status_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.system')),
            ],
            options={
                'verbose_name': 'API client',
                'verbose_name_plural': 'API clients',
                'ordering': ('-date_created',),
            },
        ),
    ]
