# Generated by Django 5.1.7 on 2025-07-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('core', '0016_alter_notification_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
