name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: stevendegwa/notification_bus:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Run deployment commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.NOTIFICATION_BUS_SERVER_IP }}
          username: ${{ secrets.NOTIFICATION_BUS_SSH_USER }}
          port: 22
          key: ${{ secrets.NOTIFICATION_BUS_PASSWORD_SSH_KEY }}
          script_stop: true
          script: |
            sudo chown -R $USER:$USER /srv/apps/live/notification-bus
            cd /srv/apps/live/notification-bus/
            git config --global --add safe.directory /srv/apps/live/notification-bus
            git pull origin main
            docker-compose pull
            docker-compose up -d --build
            docker-compose exec -T app python manage.py migrate
            docker-compose exec -T app python manage.py collectstatic --no-input
